# fvm flutter pub global run melos bootstrap
# fvm flutter pub global run melos bootstrap
name: reactive_forms_widgets
packages:
  - packages/**
  - packages/**/example
ignore:
  - "packages/**/example"
  - "packages/reactive_forms_widget_package/**"
  - "packages/.mason"
  - "packages/mason.yaml"
  - "packages/mason-lock.json"

ide:
  intellij:
    enabled: true

runPubGetInParallel: true